### PR TITLE
Implement storage

### PR DESCRIPTION
**Pull request by lowjiayee**
- Can load/store events, and their respective attendances & performances

Potential problem:
- AttendanceList and PerformanceList might not be linked to Event yet.

### CODE REVIEW

**Comment by benchan911** [comment]
Can this also stored studentListCollection in a separate file?

**Comment by lowjiayee** [comment]
Yes, will do

**Comment by benchan911** [comment]
> * Can load/store events, and their respective attendances & performances
> 
> Potential problem:
> 
> * AttendanceList and PerformanceList might not be linked to Event yet.

AttendanceList and PerformanceList are linked to Event. The attendance related commands and performance related commands directly modify the existing attendanceList and PerformanceList inside the Event once created by accessing it via the eventName

**Review by benchan911 — COMMENTED** [review]
can we store all the text files into a folder called data? So at least its cleaner to extract for the user? Just a suggestion

**Comment by lowjiayee** [comment]
Yes the idea is good, but I can't read both events and studentLists from the same file as of now.

It's a possible idea for v2.1

**Comment by benchan911** [comment]
> Yes the idea is good, but I can't read both events and studentLists from the same file as of n

the files can be separated, but found in the same folder

**Comment by lowjiayee** [comment]
Ooh that's a good idea, will do that

**Pull request merged**
